FuelLabs/fuel-merkle

src/binary.rs
src/binary/hash.rs
src/binary/merkle_tree.rs
src/binary/node.rs

- https://github.com/FuelLabs/fuel-merkle/issues/31
- https://github.com/FuelLabs/fuel-merkle/issues/28
This PR refactors the binary node interface to add the following properties:
- Binary module reuses types from the common module instead of recreating them (e.g., using `use common::Bytes32` instead of `type Data = [u8; 32]`)
- Binary node encapsulates internal logic for calculating hash sums, setting child/parent keys, etc.
- Binary Merkle tree is now agnostic of binary node internal logic
- Simplifies code overall
This PR puts the code into a better position for future feature development by improving encapsulation and decreasing coupling between the binary node and tree structures. In a future PR, BMT nodes will be refactored to use positional  paths and traversal. …

Refactor: Binary node interface and encapsulation

---

Cargo.toml
src/binary/merkle_tree.rs
src/binary/node.rs

- Closes https://github.com/FuelLabs/fuel-merkle/issues/31
- Progresses https://github.com/FuelLabs/fuel-merkle/issues/28
This PR replaces the existing method of Binary Merkle Tree traversal with positional path iteration introduced in a previous PR https://github.com/FuelLabs/fuel-merkle/pull/55. This allows the binary tree storage to use integer (`u64`) keys, rather than hash (`Bytes32`) keys. For dense trees, such as BMTs, integer keys are better suited than hash keys for the underlying storage backing. This is because dense trees operate on their running count of leaves. This count is used when generating storage keys. 
This approach has a number of strong advantages:
- Positional path traversal does not require storage loads, allowing a clean separation between …

Feat: BMT prove uses position path

---

src/binary/merkle_tree.rs
src/common.rs

- Closes #28 
This PR adds the ability to load a Binary Merkle tree from storage, given a storage reference and number of leaves. 
The binary Merkle tree class exposes the static method `load`, and takes the storage reference and number of leaves as arguments. This method returns a result: if the tree can be built from the storage reference, the built tree is returned; otherwise, an error is returned.
Building the tree from storage is done by reading the leaf nodes from the storage, and iteratively calculating the internal nodes. This approach requires that the storage has all the leaf nodes stored for the tree described by the `leaves_count` argument. It does not require that any internal nodes be calculated and stored beforehand. This makes the approach suitable for …

Feat: Binary merkle tree load from storage

---

src/common.rs
src/sparse.rs
src/sparse/node.rs

- Closes https://github.com/FuelLabs/fuel-merkle/issues/59
This PR addresses an outstanding `todo` introduced in https://github.com/FuelLabs/fuel-merkle/pull/55.
This PR adds a height member to the Sparse Merkle Tree node. The node's underlying buffer has been extended by four bytes to accommodate a `u32` height field. The node's height is now stored inside the first four bytes, and the existing members (prefix, bytes lo, bytes hi) have been moved back. This makes the total buffer size 69 bytes.
While height is now part of the node's buffer, its height is not included in the node's hash. This means a node hash is still calculated as `h(0x01 | left_key | right_key)`. Instead of hashing the entire buffer, we simply hash a slice of the buffer at the relevant range.
Height is …

Feat: Add height to sparse node

---

src/sparse/node.rs

The current SMT implementation hashes keys provided by calls to `update` and `delete`. The [SMT spec](https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#sparse-merkle-tree) mandates leaves use the raw 32 byte key input, rather than the hash of the key input. This means clients are able to decide on the algorithm that produces 32 byte keys. 
This behaviour is an artifact of the Celestia SMT implementation. Both the Celestia implementation and the Fuel implementation are moving towards an SMT interface that takes in 32 byte keys for `update` and `delete` functions.
In this PR, I am changing the internal SMT node structure so that leaves are constructed using raw 32 byte keys. The [WIP SMT PR](https://github.com/FuelLabs/fuel-merkle/pull/41) has been …

Fix: Remove hashing from leaf keys in SMT Node

---

src/sparse/node.rs

Minor refactor to SMT Node to provide interface for setting the node prefix. This allows setting the node prefix by specifying the prefix bit, rather than the prefix bit as an array. This PR introduces no functional changes.

Refactor: Add method to SMT node to set prefix

---

src/sparse/node.rs

Adds a field for displaying `height` when debugging an SMT `Node` or `StorageNode`. When debugging with a call like 
```
println!("{:?}")
```
it will output something like:
```
Node (Internal) { Height: 1, Hash: "eda830b210c5332b6d899718c55d04eaa942d99a70deaa6e39905eb393edd480", Left child key: "40fec866539985c2212facbbbde0477e92700fa0b96614c239add059b8812e2a", Right child key: "e08d1bf00caa0f7ebdb18f922519c02c7e613a5d63e0ede94b6b6657ed1713b6" }
```
This is useful when debugging the SMT implementation. For example, when setting the SMT root, it is necessary that the supplied node has a height of 256.

Feat: Add height to SMT node debug

---

src/sparse/node.rs

When retrieving a left child or right child from an SMT node, we must accommodate the case when the child is a placeholder. The placeholder node is a node with the zero sum key (`000...`). In the current design, all children must be present in the underlying data store; this includes placeholders. This assumes that the store will be initialized with a zero-sum key mapped to a placeholder, i.e.
```
...
let zero_sum_key = zero_sum()
assert!(storage[zero_sum_key].is_placeholder())
```
This has a few important drawbacks:
- The store must be initialized properly to handle this edge case. This means a storage write when initializing an SMT
- Reading a zero sum key incurs a round trip to the store, when the child can be resolved client side
- Deleting path nodes or side nodes may involve …

Fix: SMT Node `left_child` and `right_child` return placeholder when key is zero sum

---

src/sparse/node.rs

When creating an internal SMT node by merging two child nodes, the height of the merged node is equal to the height of highest child node plus 1. This is not reflected in the current implementation.
Currently, the `create_node` method assumes that the left child will always have the greater height of the left and right children. This is an artifact of the binary Merkle tree implementation where this assumption holds true. In a sparse Merkle tree, it is possible that either the left or right child will have the greater height.

Fix: When creating internal SMT node, set height to be the greater height of left and right children

---

docs/test-specs/sparse_merkle_tree_tests.md

For the test `Test Update Sparse Union`, there is a discrepancy between the expected root in the test spec, and the expected root in the test pseudocode. This appears to have been caused by committing a cardinal sin: copying + pasting a previous test case. The test spec specifies the correct root, while the pseudocode example uses an old root. This PR fixes that so that both instances reflect the correct root.

Docs: Fix expected root in SMT root test pseudocode example

---

tests-data/tests-data.rs

- Closes https://github.com/FuelLabs/fuel-merkle/issues/81
This PR adds string ref constants for the actions and encodings available to the SMT data driven test framework. This includes the actions: `"update"` and `"delete"`, as well as the encodings: `"hex"`, and `"utf-8"`.

Feat: Use constants and enums for test framework actions and encodings

---

Cargo.toml
src/binary/merkle_tree.rs
src/sparse/merkle_tree.rs

- Closes https://github.com/FuelLabs/fuel-merkle/issues/84
This PR updates the BMT and SMT interfaces to return `anyhow::Result` instead of the core `Result`. `anyhow::Result` is almost a drop-in replacement for `Result<T, Box<dyn std::error::Error>>` but allows us to omit the boxed error trait object. This gives us a cleaner, more readable interface.
According to https://docs.rs/anyhow/latest/anyhow/:
- `anyhow::Result` is equivalent to `Result<T, anyhow::Error>`
- `anyhow::Error` works a lot like `Box<dyn std::error::Error>`, but with these differences:
- Error requires that the error is `Send`, `Sync`, and `'static`.
- Error guarantees that a backtrace is available, even if the underlying error type does not provide one.
- Error is represented as a narrow pointer — …

Feat: Refactor BMT and SMT interfaces to use `anyhow::Result`

---

src/common/path_iterator.rs
src/common/position.rs
src/common/position_path.rs
src/sparse/merkle_tree.rs
src/sparse/node.rs
test-helpers/src/binary/verify.rs

Related issues: 
- Closes https://github.com/FuelLabs/fuel-merkle/issues/85
This PR reformats block comments across all files in the repo to not exceed a line length of 80 characters. Where a comment exceeds 80 characters, a line break is inserted before the hanging word such that the line length is 80 characters or less. In cases where this rule cannot be applied, the line length is left unchanged (i.e., URLs, diagrams, etc.).
Originally, I investigated using a `rustfmt.toml` file to specify line length, and apply formatting automatically with `cargo fmt`. However, this imposes the following challenges:
- Formatting line length requires settings `comment_width` and `max_width`; both settings are only available in the nightly toolchain
- Automatic formatting gave seemingly inconsistent …

Chore: Refactor comment length to maximum of 80

---

.github/workflows/ci.yml
Cargo.toml
src/binary.rs
src/binary/hash.rs
src/binary/merkle_tree.rs
src/binary/node.rs
src/common.rs
src/common/node.rs
src/common/storage_map.rs
src/common/subtree.rs
src/lib.rs
src/sparse.rs
src/sparse/hash.rs
src/sparse/merkle_tree.rs
src/sparse/node.rs
src/sum/hash.rs
src/sum/merkle_tree.rs
src/sum/node.rs

It is desirable to have no-std support so the consumers will have more
flexibility of use with this library, provided an appropriate storage
backend.
This functionality will support the usage of contracts in fuel-tx, since
its id is calculated with a binary merkle tree, according to fuel specs.

Add no-std support

---

src/binary/merkle_tree.rs
src/common.rs
src/common/msb.rs
src/common/path_iterator.rs
src/common/position_path.rs
src/common/storage_map.rs
src/lib.rs
src/sparse/merkle_tree.rs
src/sparse/node.rs
src/sum/merkle_tree.rs
tests-data/tests-data.rs

- Closes #89 
Currently, binary and sparse Merkle tree functions are defined to throw a `storage_map::StorageError` on error; errors internal to the Merkle tree arising from an invalid state or operation (`MerkleTreeError`) are cast to `StorageError` to accommodate this interface. 
One issue with this approach is that the Merkle tree interfaces are coupled to the `storage_map::StorageError` type. A superior approach is to define Merkle tree types with a generic `StorageType`, where a `StorageType` is an implementor of the `fuel_storage::Storage` trait and encapsulates a storage-specific error. This allows the Merkle tree interfaces to decouple from the `storage_map::StorageError` and to instead define function error types generically over the `StorageType`'s error. By …

Debt: Refactor Merkle tree error propagation and handling

---

Cargo.toml
src/binary/merkle_tree.rs
src/common.rs
src/common/storage_map.rs
src/sparse/merkle_tree.rs
src/sparse/node.rs
src/sum/merkle_tree.rs

- Closes #91 
This PR replaces the `StorageMap`'s usage of the standard `HashMap` with a drop-in replacement from `hashbrown`. `hashbrown::HashMap` provides identical functionality without the use of `std`. 
This enables consumer libs to use `fuel_merkle::StorageMap` in a non-`std` context. Client code that uses Merkle trees can now use the `StorageMap` as the default in-memory storage backing without implementing their own non-`std` storage.
This also enables the unit tests within `fuel_merkle` to execute without the `std` feature flag. This allows us to verify behaviour in both the `std` and non-`std` environments. Currently, CI runs tests with `std`; in the future, CI will additionally run tests without the `std` flag. 
This PR is currently built off of the work in #94 …

Feat: Enable use of StorageMap without `std` feature 

---

src/binary/merkle_tree.rs
src/sparse/in_memory.rs
src/sparse/merkle_tree.rs
src/sum/merkle_tree.rs
tests-data/tests-data.rs

It is perfectly fine to use generic as storage and not its reference, as `Storage` implements `&mut` for its trait here: https://github.com/FuelLabs/fuel-storage/blob/21319d8412edda0dc1387ca201408ccb8c112d6b/src/lib.rs#L43
And rust will be able to match both storage and &mut storage bcs of that.
Added change for both sparse and sum Merkle tree

Relax constraint on Storage

---

src/binary/merkle_tree.rs
src/sparse.rs
src/sparse/in_memory.rs
src/sparse/merkle_tree.rs
src/sum/merkle_tree.rs
tests-data/tests-data.rs

- Closes https://github.com/FuelLabs/fuel-merkle/issues/93
This PR adds an infallible, in-memory type for the Sparse Merkle Tree. 
Because the default in-memory storage type, `StorageMap`, is infallible, i.e. never returns an error, we know that the wrapping SMT is also infallible for common storage based operations, specifically `update` and `delete`. 
The in-memory type prescribes using the default `StorageMap` as its storage type. This allows us to simplify the signature of the in-memory SMT constructor by removing the need to supply a storage reference. Instead, the in-memory SMT owns a storage instance of type `StorageMap`, and internally constructs a regular SMT around this storage. 
This creates a self-referential structure: the internal SMT refers to the the …

Feat: Infallible in-memory SMT 

---

src/binary/merkle_tree.rs
src/common/position_path.rs
src/common/storage_map.rs
src/lib.rs
src/sparse/merkle_tree.rs
src/sparse/node.rs
src/sum/merkle_tree.rs
src/sum/node.rs
test-helpers/src/binary/merkle_tree.rs
tests-data/tests-data.rs

Resolving `cargo clippy` lints.
Added two exceptions used only in tests:
* `clippy::bool_assert_compariso` for `assert_eq!(Position(0).is_leaf(), true);`
* `clippy::identity_op` for `FEE * 1` as it gives better clarity to have that number.
and we probably need to add `clippy` to ci: https://github.com/FuelLabs/fuel-merkle/issues/102

cargo clippy lints

---

.github/workflows/ci.yml

- Closes https://github.com/FuelLabs/fuel-merkle/issues/102
This PR updates the github CI script to include a job for running Clippy. 
The existing `build` job is now broken up into multiple jobs to better communicate their purpose:
- `check-formatting`
- `check-clippy`
- `build-and-test`
- `build-and-test-no-std`
Finally, the `publish` job now depends on the success of all the jobs prior.
This PR needs admin assistance to update the protected branch rules for master to account for the new CI job names - cc: @adlerjohn

Add clippy job to CI

---

.github/workflows/ci.yml
src/binary/in_memory.rs
tests-data/tests-data.rs

- Closes #107 
- Closes #45 
This PR accomplishes the following:
- During CI, use the `cargo check` command over `cargo build`. See [cargo check docs](https://doc.rust-lang.org/cargo/commands/cargo-check.html) for details.
- During CI, `cargo check` will fail if any compiler warnings are present in the code. This is accomplished by setting the environment variable `RUSTFLAGS="-D warnings"`
- Fixes some warnings discovered by Clippy

Use `check` in CI

---

src/binary/in_memory.rs
src/binary/merkle_tree.rs

Related PRs:
- Closes #14
As per the binary Merkle tree specification we use, defined by [RFC 6962](https://www.rfc-editor.org/rfc/rfc6962), the binary Merkle tree proof set does not include the leaf for which we are proving. Therefore, this PR removes that leaf from the generated proof set. 
Note: We do not currently implement proofs for BMSTs so this PR does not modify any behaviour in that area.

debt: Remove first leaf from BMT proof set

---

src/binary/in_memory.rs
src/binary/merkle_tree.rs

This reverts PR #115, commit bf201991ae06353259d980f2633ba764a17980f2.
It turns out that removing the first leaf from the BMT proof set makes it incompatible with the current implementation of proof verification in `test-helpers/src/binary/verify.rs`.  Proof sets without the first leaf (the leaf being proven) are incomplete; the first leaf is required in order to allow the proof set to be properly hashed together to form the root signature. 
The previous PR removed the first leaf from the public implementation of the proof sets. However, the reference implementation began to fail its verification test suite once I updated it to remove the first leaf from its proof sets. Therefore, I am reverting the change to remove the first leaf from the public implementation in order to maintain parity …

Revert #115

---

Cargo.toml
src/binary/hash.rs
src/sparse/hash.rs
src/sum/hash.rs
test-helpers/Cargo.toml

Clippy errors are causing other PRs to fail CI.

Clippy and dependency upgrades

---

src/common.rs
src/common/msb.rs
src/common/path.rs
src/common/path_iterator.rs
src/sparse/node.rs

- Untracked
This PR introduces a small layer of abstraction on top of the `Msb` trait to provide "node-level" functionality, such as getting path instructions. These functions make use of the existing `Msb` functions, like retrieving specific bits, by wrapping them in higher level functions designed for use in Merkle trees and nodes. The `Path` trait and `Instruction` enum can now better communicate the intention of the algorithms with this higher level vocabulary.
This also introduces better type safety by using enums that describe the full range of path instructions (Left or Right) rather than 0 or not 0. Lastly, this PR removes an instance of an `expect` that may result in a panic under certain circumstances.

refactor: Introduce `Path` trait and `Instruction`
